controller_list:

  - name: fake_right_arm_controller
    joints:
      - m0
      - m10
      - m11
      - m12
      - m13
      - m14

  - name: fake_right_eef_controller
    joints:
      - m15
      - m17

  - name: fake_left_arm_controller
    joints:
      - m0
      - m20
      - m21
      - m22
      - m23
      - m24

  - name: fake_left_eef_controller
    joints:
      - m25
      - m27